
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./ClientWrapper";
import Navbar from "./Navbar";
const inter = Inter({ subsets: ["latin"] });
import WithoutProviderWrapper from "./WithoutProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >

        <ClientWrapper>
          <Navbar />
          <WithoutProviderWrapper>
            {children}
          </WithoutProviderWrapper>

        </ClientWrapper>
      </body>
      <div id="globalLoader" className="fixed z-[9999] top-1/2 left-1/2 bg-white w-full h-full flex justify-center items-center">
        <div className="flex justify-center items-center h-screen">
          <img src="loading.gif" alt="loading image" />
        </div>
      </div>
    </html>
  );
}
